# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [502]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [503]:
A = np.arange(1, 16).reshape(3, 5)

In [504]:
print("dimension: ", A.ndim)
print("shape: ", A.shape)
print("size: ", A.size)
print(type(A))

dimension:  2
shape:  (3, 5)
size:  15
<class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [505]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [506]:
print("elementwise subtraction:\n", B - C)
print("elementwise multiplication:\n", B * C)
print("matrix multiplication:\n", B @ C)

elementwise subtraction:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
elementwise multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
matrix multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [507]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [508]:
print("exponentiate each number elementalwise:\n", np.exp(B))
print("\nthe minimum value in the whole matrix:\n", np.min(B))
print("\nthe miminum value in each row:\n", np.min(B, axis=1))
print("\nthe minimum value in each column:\n", np.min(B, axis=0))
print("\nindex for the minimum value in the whole matrix:\n", np.argmin(B))
print("\nindex for the minimum value in each row:\n", np.argmin(B, axis=1))
print("\ncalculate the sum for all elements:\n", np.sum(B))
print("\ncalculate the mean for each column:\n", np.mean(B, axis=0))
print("\ncalculate the median for each column:\n", np.median(B, axis=0))

exponentiate each number elementalwise:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

the minimum value in the whole matrix:
 1

the miminum value in each row:
 [1 4 7]

the minimum value in each column:
 [1 2 3]

index for the minimum value in the whole matrix:
 0

index for the minimum value in each row:
 [0 0 0]

calculate the sum for all elements:
 45

calculate the mean for each column:
 [4. 5. 6.]

calculate the median for each column:
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [509]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [510]:
print(A[1])

[ 6  7  8  9 10]


**Answer:**

You get the element in an array with indices. -> arr[1] returns the element in index 1

A is a 2-dimensional array which consists of multiple array elements.
This means that each element is defined by two subscripts, the row index and the column index.

        A[row, column] = element in A

        A[row] = row in A
Missing indices are seen as [ : ] and A[0] returns the whole array in index 0.



### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [511]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [512]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


**Answer**

There's two ways.

Method 1: 

In [513]:
for x in A:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


Method 2:

In [514]:
for x in A.flat:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [515]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print("-------------")

print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
-------------
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


**Answer**

B is an 3-dimensional array.\
It contains mulitple 2-dimensional arrays\
Which means that you need to provide 3 indices to access the 'non-array' elements.

        B[matrix, row, column] = element
Thorough explanation below:\
Easy way to demonstrate how a 3-dimensional array works is by iterating through all elements with for loops.

In [516]:
for z in b:                     # z is the highest dimension and can be accessed through the first index. Example b[0]
    print(z)
    for x in z:                 # x-elements are accessible in specified z. b[z, x]
        print('------------')
        print(x)
        for y in x:             # y-elements are accessible in specified z and x. b[z, x, y]
            print("Element:", y)
    print('* * * * * * * * * * *')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[0 1 2 3 4]
Element: 0
Element: 1
Element: 2
Element: 3
Element: 4
------------
[5 6 7 8 9]
Element: 5
Element: 6
Element: 7
Element: 8
Element: 9
------------
[10 11 12 13 14]
Element: 10
Element: 11
Element: 12
Element: 13
Element: 14
* * * * * * * * * * *
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
------------
[15 16 17 18 19]
Element: 15
Element: 16
Element: 17
Element: 18
Element: 19
------------
[20 21 22 23 24]
Element: 20
Element: 21
Element: 22
Element: 23
Element: 24
------------
[25 26 27 28 29]
Element: 25
Element: 26
Element: 27
Element: 28
Element: 29
* * * * * * * * * * *


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [517]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [518]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [519]:
A = np.arange(1, 5).reshape(2, 2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [520]:
def add_mult_matrices(m1, m2, operator=""):

    if not isinstance(m1, np.ndarray):
        return f"{m1} is of type {type(m1)}. Please provide a numpy.ndarray"
    elif not isinstance(m2, np.ndarray):
        return f"{m2} is of type {type(m2)}. Please provide a numpy.ndarray"

    print(f"Matrix 1:\n{m1}\nMatrix 2:\n{m2}\n")
    result = 0
    if operator == "add":
        if m1.shape != m2.shape:
            return f"Can't add, the m1 and m2 aren't the same size."
        result = m1 + m2
    elif operator == "multiply":
        if m1.shape[-1] != m2.shape[0]:
            return f"Can't multiply, m1 columns and m2 rows incompatible."
        result = m1 @ m2
    else:
        return "Choose either add or multiply"

    return f"{operator}ing gave the following:{result}"


testA = np.arange(1, 7).reshape(3, 2)
testB = np.array([2, 2])

print(add_mult_matrices(testA, testB, "multiply"))

Matrix 1:
[[1 2]
 [3 4]
 [5 6]]
Matrix 2:
[2 2]

multiplying gave the following:[ 6 14 22]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [521]:
x = np.array([4, 3]).reshape(1, 2)
print("Uppgift 10.1.1")
print(f"a) dimension: {x.shape}")
print("b) 5x =", x * 5)
print("c) 3x =", x * 3)
print("d) 5x + 3x =", (x * 5) + (x * 3))
print("e) 8x =", x * 8)
print("f) 4x - x =", (x * 4) - x)
print("g) x^t, vilken blir den nya dimensionen?")
print(f"{np.transpose(x)},\nnya dimensionen är {np.transpose(x).shape}")
print("h) är x + x^t definierat? : Nej för att dimensionerna inte är identiska.")
print("i) ||x|| =", np.linalg.norm(x))

Uppgift 10.1.1
a) dimension: (1, 2)
b) 5x = [[20 15]]
c) 3x = [[12  9]]
d) 5x + 3x = [[32 24]]
e) 8x = [[32 24]]
f) 4x - x = [[12  9]]
g) x^t, vilken blir den nya dimensionen?
[[4]
 [3]],
nya dimensionen är (2, 1)
h) är x + x^t definierat? : Nej för att dimensionerna inte är identiska.
i) ||x|| = 5.0


In [522]:
v = np.array([3, 7, 0, 11]).reshape(4, 1)
print("Uppgift 10.1.2")
print(f"a) dimension: {v.shape}")
print("b) 2v =\n", v * 2)
print("c) 5v + 2v =\n", (v * 5) + (v * 2))
print("d) 4v - 2v =\n", (v * 4) - (v * 2))
print("e) v^t, vilken blir den nya dimensionen?")
print(f"{np.transpose(v)}, nya dimensionen är {np.transpose(v).shape}")
print("f) ||v|| =", np.linalg.norm(v))

Uppgift 10.1.2
a) dimension: (4, 1)
b) 2v =
 [[ 6]
 [14]
 [ 0]
 [22]]
c) 5v + 2v =
 [[21]
 [49]
 [ 0]
 [77]]
d) 4v - 2v =
 [[ 6]
 [14]
 [ 0]
 [22]]
e) v^t, vilken blir den nya dimensionen?
[[ 3  7  0 11]], nya dimensionen är (1, 4)
f) ||v|| = 13.379088160259652


In [523]:
v1 = np.array([4, 3, 1, 5]).reshape(1, 4)
v2 = np.array([2, 3, 1, 1]).reshape(1, 4)
print("Uppgift 10.1.3")
print("a) ||v1|| =", np.linalg.norm(v1))
print("b) ||v1 - v2|| =", np.linalg.norm(v1 - v2))

Uppgift 10.1.3
a) ||v1|| = 7.14142842854285
b) ||v1 - v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

**Uppgift 10.2.1** Om det är definierat, utför följande beräkningar:

In [524]:
A = np.array([2, 1, -1, 1, -1, 1]).reshape(2, 3)
B = np.array([4, -1, 1, 2, -4, -2]).reshape(2, 3)
C = np.array([1, 2, 2, 1]).reshape(2, 2)
D = np.array([3, 4, 4, 3]).reshape(2, 2)
E = np.array([1, 2]).reshape(2, 1)
I = np.array([1, 0, 0, 1]).reshape(2, 2)

In [525]:
print("a) 2A =\n", A * 2)
print("b) B - 2A =\n", B - (A * 2))
print("c) 3C - 2E =\n Ej Definierat: Subtraktion mellan 2x2 och 2x1.")
print("d) 2D - 3C =\n", (D * 2) - (C * 3))
print("e) D^t + 2D =\n", np.transpose(D) + (D * 2))
print("f) 2C^t - 2D^t =\n", (np.transpose(C) * 2) - (np.transpose(D) * 2))
print("g) A^t - B =\n Ej Definierat: Subtraktion mellan 3x2 och 2x3.")
print("h) AC =\n Ej Definierat: Multiplikaiton mellan 2x3 och 2x2.")
print("fortsättning...")

a) 2A =
 [[ 4  2 -2]
 [ 2 -2  2]]
b) B - 2A =
 [[ 0 -3  3]
 [ 0 -2 -4]]
c) 3C - 2E =
 Ej Definierat: Subtraktion mellan 2x2 och 2x1.
d) 2D - 3C =
 [[3 2]
 [2 3]]
e) D^t + 2D =
 [[ 9 12]
 [12  9]]
f) 2C^t - 2D^t =
 [[-4 -4]
 [-4 -4]]
g) A^t - B =
 Ej Definierat: Subtraktion mellan 3x2 och 2x3.
h) AC =
 Ej Definierat: Multiplikaiton mellan 2x3 och 2x2.
fortsättning...


In [526]:
print("i) CD =\n", C @ D)
print("j) CB =\n", C @ B)
print("k) CI =\n", C @ I)
print("l) AB^t =\n", A @ np.transpose(B))

i) CD =
 [[11 10]
 [10 11]]
j) CB =
 [[ 8 -9 -3]
 [10 -6  0]]
k) CI =
 [[1 2]
 [2 1]]
l) AB^t =
 [[6 2]
 [6 4]]


**Uppgift 10.2.2** Beräkna AA<sup>t</sup>

In [527]:
A = np.array([2, 3, 4, 5, 4, 1]).reshape(2, 3)
print(A @ np.transpose(A))

[[29 26]
 [26 42]]


**Uppgift 10.2.3** Verifiera att AB = AC men att B != C.

In [528]:
A = np.array([1, 2, 2, 4]).reshape(2, 2)
B = np.array([2, 1, 1, 3]).reshape(2, 2)
C = np.array([4, 3, 0, 2]).reshape(2, 2)

print('AB:\n',A @ B, "\nAC:\n", A @ C)

AB:
 [[ 4  7]
 [ 8 14]] 
AC:
 [[ 4  7]
 [ 8 14]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [529]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [530]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [531]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


Has already been answered.